### ISSUE TITLE
Topology view shows many unexpected IP that visit my Kafka pod

### ISSUE THREAD

**Issue by J-lena** [Kindling-project/kindling#138]
**What did you expect to see?**
A pod visit this Kafka-0.

**What did you see instead?**
lots of IP visit Kafka

**Screenshots**
![image](https://user-images.githubusercontent.com/97420104/159646669-8219c871-70df-417c-bf2c-0a200ef2c272.png)

**Comment by jundizhou** [comment]
First of all, we have to make it clear that our scope is kubernetes. So I don't think we even need to show requests that can't relate kubernetes resources

**Comment by J-lena** [comment]
@jundizhou it seems that those IP are all pod IP

**Comment by jundizhou** [comment]
> @jundizhou it seems that those IP are all pod IP

Then this is really a bug @thousandxu

**Comment by dxsup** [comment]
Could you please query the original data manually from your Prometheus? The PromQL could be like `rate(kindling_topology_request_duration_nanoseconds_count{dst_pod="kafka-1",src_ip="192.168.209.236"}[30s])`.

**Comment by J-lena** [comment]
@dxsup Empty in 30s. but there are three records in two days.
![image](https://user-images.githubusercontent.com/97420104/159672810-7df95d10-14e7-49ec-bfe3-96f7de6c620b.png)

**Comment by J-lena** [comment]
@dxsup Here are the recordes in two days
![image](https://user-images.githubusercontent.com/97420104/159824483-94d0a5b9-bd54-44ed-b3b3-6fadc8beaec0.png)

**Comment by dxsup** [comment]
From the first screenshot, we can see there are lots of different IPs which call the same destination `kafka-1`. Since you said they should have been some Pods, I suspected that they are all short-lived Pods in which case each one was deleted and a new one was created quickly, so I suggested you query the original data to see whether it was what I suspected. 

The second screenshot shows that a container `apm-data-analyzer` with an id of `bb0104ca688f` was found with and without the Pod metadata, and the latter metric is much less than the formal one. It is much likely what I suspected above, that is each Pod was deleted and a new one was created quickly. The most effective way to verify if it is true is to query the data using the following PromQL:
```
rate(kindling_topology_request_duration_nanoseconds_count{dst_pod="kafka-1", src_ip=~"192.168.209.*"}[2d])
```
If the result shows multiple metrics behave the same as the second screenshot for each `src_ip`, then that is it.

No matter whether your issue is caused by that, there is actually a similar risk existing for our collector now. When a workload deletes and creates its controlled Pods quickly as a cycle, the collector is possibly unable to catch up with the update of the Pod metadata, in which case the metrics for the calls made before we get the metadata will lose some labels including `pod`, `workload_name`, `workload_kind`, etc.

I haven't had good ideas on how to fix it. Maybe we could cache the metrics temporarily when we can't find the Pod metadata and wait for a second to check it again. But the problem is how long the metrics could be cached? I think it is a trade-off between the Memory/CPU resource consumption and the correctness of the metrics. What would you like to say about this issue? @NeJan2020

**Comment by J-lena** [comment]
@dxsup @NeJan2020  I don't think it's reasonable. The screenshot shows that the secondary record with pod metadata  has the same container id with the last record without such data, so I think it means the pod is not a short-lived(one was created quickly and deleted immediately) pod.  I think  a  pod can produce a network request  that means pod is ready, In theory the  agent can watch the creation of pod. But why agent doesn't get those infors.

**Comment by dxsup** [comment]
My apologies. Your issue is certainly NOT caused by short-lived pods. But my guess about the root cause does not change. Due to the slow update of the metadata cache, the collector cannot find the metadata of the fresh Pods immediately, but after a few seconds, it can. We will conduct some tests and dig into this scenario to try to figure out whether the root cause is like what we guess.

**Comment by NeJan2020** [comment]
This Problem seems caused by the `Graceful delete` in K8s.
K8s will firstly send a  SIGTERM to the process which PID=1 in a container and wait for it to shutdown gracefully.

For now, our agent will directly remove the info of the container from the cache once it watched the container's delete event, while the pod is not deleted actually, and keep sending requests in a few seconds.

When the final requests were captured by the agent, the agent would not find its container's info and mark this request as a "NOT FOUND INTERNAL", which means this request is from the k8s cluster we monitored, but no container info was found. Here is an example of when we gracefully delete pod.

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/64676199/160050092-4476d5a6-b580-40ed-9d23-41133b1115a6.png">

This problem may also happen in dst_info because the IP: PORT info was cached by the same logic.

We will add a delete queue to make sure when we delete the container info, the pod is actually deleted soon.
