### ISSUE TITLE
The external network traffics are not being traced 

### ISSUE THREAD

**Issue by J-lena** [Kindling-project/kindling#46]
**Describe the bug**
Hi, I want to identify the specific source that leads to the heavy traffics on my ingress workload. But in the  topology dashboard, i can't see the external IP  to my ingress workload, it seems that the  external network traffics are not being traced 
**How to reproduce?**
Visit your ingress from outside the Kubernetes cluster

**What did you expect to see?**
External IP to ingress must be displayed

**What did you see instead?**
No node sends traffic to my ingress workload
**Screenshots**
![image](https://user-images.githubusercontent.com/97420104/154442933-3f4a6545-b892-4117-b1ed-dd8ba939bf13.png)

**Comment by dxsup** [comment]
What you saw is what we expect now. The metrics of `kindling_topology_xxx` are all generated from the data scraped from the client-side, and apparently, we can't get any data when the client is not monitored. That's why the dashboard doesn't display any source IP that is outside the cluster as a client. 

If we want to display this information, we could use the data scraped from the server-side as the mimic of the one from the client-side. But the problem is that it could introduce many new unexpected issues since the data sometimes is not the one we want.

As explained above, I think this issue is not a bug but a "feature request". We'll talk about this feature later and now I prefer to remove the "bug" label.
