### ISSUE TITLE
The probe terminated by error: libprotobuf CHECK failed

### ISSUE THREAD

**Issue by dxsup** [Kindling-project/kindling#50]
**Describe the bug**
The probe terminated by error.

**How to reproduce?**
I can't reproduce the bug.

**Screenshots**
<img width="444" alt="untitled" src="https://user-images.githubusercontent.com/46807570/154654206-e7dc6ba8-b87e-4578-879f-0a3c837068c6.png">

**Logs**
The log file is attached. There is some important information which is as follows.
[probe-crash.txt](https://github.com/Kindling-project/kindling/files/8095862/probe-crash.txt)

> [libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/message_lite.cc:360] CHECK failed: target + size == res: 
terminate called after throwing an instance of 'google::protobuf::FatalException'

**Environment (please complete the following information)**
- Kindling agent version: v0.1.0
- Node OS version: Alibaba Cloud Linux (Aliyun Linux) 2.1903 LTS (Hunting Beagle)
- Node Kernel version: 4.19.91-23.al7.x86_64
- Kubernetes version: v1.20.4-aliyun.1

**Comment by zjuzzb** [comment]
![lQLPDhsooUJWq5vNAtzNBWuw2-MeRHO7rP8CEz3DE4A-AA_1387_732](https://user-images.githubusercontent.com/34501766/154658941-d6ed04f6-64b9-4baf-b0af-6afe954c00b5.png)
As the function stack showes, the problem is caused by publisher when serializing messages. Maybe it's a corrupted message, please check it out @sanyangji

**Comment by jundizhou** [comment]
At first we thought it was caused by concurrency, but now it seems that it is really caused by corrupted messages @zjuzzb

**Comment by sanyangji** [comment]
> ![lQLPDhsooUJWq5vNAtzNBWuw2-MeRHO7rP8CEz3DE4A-AA_1387_732](https://user-images.githubusercontent.com/34501766/154658941-d6ed04f6-64b9-4baf-b0af-6afe954c00b5.png)
> As the function stack showes, the problem is caused by publisher when serializing messages. Maybe it's a corrupted message, please check it out @sanyangji
I have already checked, but have no idea on it. It will be helpful if the bug can be reproduced.
One guess is that due to the concurrent problem, but @jundizhou reviewed the codes but found nothing.

**Comment by sanyangji** [comment]
I have confirmed the issue is produced by concurrent bug that setting wrong kindlingEventList's m_ready value after swapping. Value True of m_ready[kindlingEventList] ensures that kindlingEventList in m_kindlingEventLists can be sent without concurrent problems.  However, I wrongly set the old kindlingEventList (the one in converter after swapping) which may cause that kindlingEventList in converter can be serialized when added new kindlingEvent. PR https://github.com/Kindling-project/kindling/pull/171 corrects it.
